#!/usr/bin/env bash

# awseasy - an AWS CLI assited scripts
#
# written by jorgedlt@gmail.com - 2016 Jun 28

#  sameAs - Colorized out
sameAs () {
  echo "${GRAY} executing command: ${GREEN} $1 ${RESET}"
}

#  sameAs - Colorized out
divText () {
  echo "${GRAY} ==== ${BLUE} $1 ${GRAY} ==== ${RESET}"
}

#  descDUMP - Colorized out
descDUMP () {
  echo "    ${GRAY}$1: [ ${YELLOW}$2 ${GRAY}] $3: [ ${YELLOW}$4 ${GRAY}]"
}

#  awstag - AWS -- Any AWS Element re-tag
awstag () {

  aws ec2 create-tags --resources "${1}" --tags Key=Name,Value="${2}"
}

source ~/.awseasy/awseasy.ec2
source ~/.awseasy/awseasy.iam
source ~/.awseasy/awseasy.vpc
source ~/.awseasy/awseasy.rds
source ~/.awseasy/awseasy.lda
source ~/.awseasy/awseasy.net
source ~/.awseasy/awseasy.asg
source ~/.awseasy/awseasy.elb
source ~/.awseasy/awseasy.gen
source ~/.awseasy/awseasy.s3c

# fin
