#!/usr/bin/env bash

# awseasy - an AWS CLI assited scripts
#
# written by jorgedlt@gmail.com - 2016 Jun 28

#  sameAs - Colorized out
sameAs () {
  echo "${GRAY} executing command: ${GREEN} $1 ${RESET}"
}

#  basedOn - Colorized out
basedOn () {
  echo "${GRAY} based on: ${GREEN} $1 ${RESET}"
}

#  alsoTry - Colorized out
alsoTry () {
  echo "${GRAY} also try: ${GREEN} $1 ${RESET}"
}

#  sideHead - Colorized out
sideHead () {
  echo; echo "${GREEN} ${1}: ${RESET}"
}

#  divText - Colorized out
divText () {
  echo "${GRAY} ==== ${CYAN} $1 ${GRAY} ==== ${RESET}"
}

#  descDUMP - Colorized out
descDUMP () {
  echo "    ${GRAY}$1: [ ${YELLOW}$2 ${GRAY}] $3: [ ${YELLOW}$4 ${GRAY}]"
}

#  singlewide - Colorized out - 1x out and no square brackets
singlewide () {
  echo "    ${GRAY}$1: ${GREEN}$2 ${GRAY}"
}

#  doublewide - Colorized out - similar to descDUMP but GREEN
doublewide () {
  echo "    ${GRAY}$1: [ ${GREEN}$2 ${GRAY}] $3: [ ${GREEN}$4 ${GRAY}]"
}

#  triplewide - Colorized out - similar to descDUMP but GREEN
triplewide () {
  echo "    ${GRAY}$1: [ ${GREEN}$2 ${GRAY}] $3: [ ${GREEN}$4 ${GRAY}] $5: [ ${GREEN}$6 ${GRAY}]"
}

###

#  awstag - AWS -- Any AWS Element re-tag
awstag () {
  aws ec2 create-tags --resources "${1}" --tags Key=Name,Value="${2}"
  sameAs 'aws ec2 create-tags --resources <InstanceId> --tags Key=Name,Value=<NewLabel>'
}

#.  awsls - AWS ALL -- Scan and display aws regions, previously ec2ls
awsls () {
   aws ec2 describe-regions | grep RegionName | cut -d':' -f2 | tr -d ' |,|"' | sort -r | uniq

   sameAs 'aws ec2 create-tags --resources <InstanceId> --tags Key=Name,Value=<NewLabel>'

   echo == More info on AWS Regions
   echo == http://docs.aws.amazon.com/general/latest/gr/rande.html
}

# the cf functions - needs to be in its own file

#.
#. AWS Cloud Front Commands
#.

#.  cfls - AWS Cloud Front -- List Cloud Front distributions
cfls ()
{
    CFlist=$( aws cloudfront list-distributions | grep -w 'Id' | egrep -v '\.|-' | cut -d':' -f2 | tr -d ' |"|:|,' );
    for CFid in $CFlist;
    do
        CFdesc=$( aws cloudfront get-distribution --id "${CFid}" );

         _CFstatus=$(_ec2parse "$CFdesc" Status);
         _CFdomain=$(_ec2parse "$CFdesc" DomainName);
         _CFtarget=$(_ec2parse "$CFdesc" TargetOriginId);

         descDUMP 'Cloud Front id' $CFid Status $_CFstatus;
         descDUMP  DomainName $_CFdomain Target $_CFtarget;

         echo ' ';
     done
     sameAs 'aws cloudfront get-distribution --id <CFid>'
 }
#

#.  cfstat - AWS Cloud Front -- Status Cloud Front distributions
cfstat ()
{
if (( $# < 1 )); then
   echo usage: Needs at least one argument {Cloud Front ID}
 return
 fi

CFid=$1
#
echo Cloud Front $CFid BETA
         CFdesc=$( aws cloudfront get-distribution --id "${CFid}" );

         _CFstatus=$(_ec2parse "$CFdesc" Status);
         _CFdomain=$(_ec2parse "$CFdesc" DomainName);
         _CFtarget=$(_ec2parse "$CFdesc" TargetOriginId);
         _CFetag=$(_ec2parse "$CFdesc" ETag);
         _CFcomment=$(_ec2parse "$CFdesc" Comment);
         _CFbucket=$(_ec2parse "$CFdesc" Bucket);
         _CFtprefix=$(_ec2parse "$CFdesc" prefix);
         _CFminttl=$(_ec2parse "$CFdesc" MinTTL);
         _CFmaxttl=$(_ec2parse "$CFdesc" MaxTTL);

         CFAllowedMethods=$( echo "$CFdesc" \
          | jq  .Distribution.DistributionConfig.DefaultCacheBehavior.AllowedMethods.Items \
          | tr '\012' ' ' | tr -s ' ' )

         CFCachedMethods=$( echo "$CFdesc" \
          | jq  .Distribution.DistributionConfig.DefaultCacheBehavior.AllowedMethods.CachedMethods.Items \
          | tr '\012' ' ' | tr -s ' ' )

         CFForwardedValues=$( echo "$CFdesc" \
          | jq  .Distribution.DistributionConfig.DefaultCacheBehavior.ForwardedValues.Headers.Items \
          | tr '\012' ' ' | tr -s ' ' )

         # CFOriginSslProtocols=$( echo "$CFdesc" \
         # | jq  .Distribution.DistributionConfig.Origins.Items.0.CustomOriginConfig.OriginSslProtocols.Items \
         # | tr '\012' ' ' | tr -s ' ' )

         descDUMP 'Cloud Front id' $CFid Status $_CFstatus;
         descDUMP  DomainName $_CFdomain Target $_CFtarget;
         descDUMP  Etag $_CFetag Comment $_CFcomment;
         descDUMP  'S3 Bucket' $_CFbucket prefix $_CFtprefix;
         descDUMP  MinTTL $_CFminttl MaxTTL $_CFmaxttl;

         echo
         singlewide ForwardedValues "$CFForwardedValues"
         singlewide AllowedMethods "$CFAllowedMethods"
         singlewide CachedMethods "$CFCachedMethods"
         # singlewide 'SSL Protocols' "$CFOriginSslProtocols"

         echo ' ';
 }

#.  cfdump - AWS Cloud Front -- Dump Cloud Front distributions JSON
cfdump ()
{
if (( $# < 1 )); then
   echo usage: Needs at least one argument {Cloud Front ID}
 return
 fi

CFid=$1
#
echo Cloud Front $CFid BETA
         aws cloudfront get-distribution --id "${CFid}" | jq .
         echo ' ';
 }

# the trails functions - needs to be in its own file

#.
#. AWS Cloud Trails Commands
#.

#.  trailsls - AWS Cloud Trails -- ls -short -summary
trailsls ()
{
  aws cloudtrail lookup-events --query Events[].EventName | tr -d '"| |,|[|]' | grep -v '^$' | sort | uniq -c | ccze -A
}

#.  trailslong - AWS Cloud Trails -- ls -long -full list
trailslong ()
{
  aws cloudtrail lookup-events --query 'Events[*].[EventId, EventName, Username]' | jq . | tr '\012' ' ' | tr '[' '\012' | tr -s ' ' | tr -d '' | tr -d '"|,|]' | sort -k2,3 | awk '{ print $2 " " $3 " " $1 }' | column -t
}

#.  trailswhat - AWS Cloud Trails -- ls -full dump based EventName & Username
trailswhat ()
{
  eWHAT=$1
  aws cloudtrail lookup-events --lookup-attributes AttributeKey=EventName,AttributeValue=${eWHAT} | jq .
}
#

#.  trailswho - AWS Cloud Trails -- ls -full dump based EventName & Username
trailswho ()
{
  eWHAT=$1
  eWHO=$2
  aws cloudtrail lookup-events --lookup-attributes AttributeKey=EventName,AttributeValue=${eWHAT} --lookup-attributes AttributeKey=Username,AttributeValue${eWHO}  | jq .
}

#.  trailsroot - AWS Cloud Trails -- ls -full dump based EventName by ROOT
trailslong ()
{
  aws cloudtrail lookup-events --lookup-attributes AttributeKey=Username,AttributeValue=root | jq .
}

#.  trailsscan - AWS Cloud Trails -- Account Wide Scan
trailsscan ()
{
    awsREGIONS=$( aws ec2 describe-regions | grep RegionName | cut -d':' -f2 | tr -d ' |,|"' | sort -r | uniq );
    for thisregion in $awsREGIONS;
    do
        echo ${RESET}$thisregion;
        export AWS_DEFAULT_REGION=$thisregion;
        EventsTR=$( aws cloudtrail lookup-events --query Events[].EventName | tr -d '"| |,|[|]' );
        [ -z "$EventsTR" ] && {
             :
         } || {
             echo "  some Events found this region $thisregion in the last 7 days";
             aws cloudtrail lookup-events --query Events[].EventName | tr -d '"| |,|[|]' | grep -v '^$' | sort | uniq -c | ccze -A ;
             echo =====================================================================
         };
     done
 }

source ~/.awseasy/awseasy.ec2
source ~/.awseasy/awseasy.iam
source ~/.awseasy/awseasy.vpc
source ~/.awseasy/awseasy.rds
source ~/.awseasy/awseasy.lda
source ~/.awseasy/awseasy.net
source ~/.awseasy/awseasy.asg
source ~/.awseasy/awseasy.elb
source ~/.awseasy/awseasy.gen
source ~/.awseasy/awseasy.s3c

# fin
